[PHP]
upload_max_filesize = 20M
post_max_size = 20M
max_execution_time = 300
memory_limit = 256M
date.timezone = Europe/Madrid

[opcache]
opcache.enable = 1
opcache.memory_consumption = 128
opcache.max_accelerated_files = 10000
opcache.revalidate_freq = 2
